// Définition de substitutions NOEMIE par défaut

const NoemieSubstitutionTableDefaut = JSON.stringify([
["TOULOUSE",[ "CPAM TOULOUSE","1"]],
["BORDEAUX",[ "CPAM BORDEAUX","1"]],
["ALBI",[ "CPAM ALBI","1"]],
["MONT DE MARSAN",["CPAM MONT DE MARSAN","1"]],
["CPAM de Rouen-Elbeuf-Dieppe-Seine-Maritime",["CPAM R.E.D.76","1"]],
["PAU",["CPAM PAU","1"]],
["PARIS",["CPAM 75 PRESTATIONS","1"]],
["AGEN",["CPAM AGEN","1"]],
["NICE",["CPAM 061 NICE","1"]],
["BAYONNE",["CPAM DE BAYONNE","1"]],
["LA ROCHELLE",["CPAM DE LA ROCHELLE","1"]],
["RODEZ",["CPAM RODEZ","1"]],
["PERIGUEUX",["CPAM PERIGUEUX","1"]],
["CARCASSONNE",["CPAM CARCASSONNE","1"]],
["VANNES",["CPAM DU MORBIHAN - COURANT","1"]],
["TARBES",["CPAM TARBES","1"]],
["VERSAILLES",["CPAM DES YVELINES","1"]],
["Organisme 901",["CAVIMAC","1"]],
["MELUN RUBELLES",["CPAM 77","1"]],
["Mutuelle INTERIALE",["INTERIALE - GESTION RO","1"]],
["NANTERRE",["CPAM HAUTS DE SEINE SEPA","1"]],
["Organisme 004110000",["CAISSE PREVOYANCE ET RETRAIT","1"]],
["MGP BOURG EN BRESSE",["SECURITE SOCIALE MGP","1"]],
["Organisme SO0010000",["CETIP CETIP","0"]],
["Organisme SP0080000" ,[ "CETIP CETIP","0"]],
["Organisme AL0010000",[ "ALMERYS","1"]],
["Organisme VM0030000",["HARMONIE MUTUELLES","1"]],
["Organisme VM0010000",["VIAMEDIS","1"]],
["Organisme AC0010000",["ACTIL SAS","1"]],
["Caisse de Ret.et Prev. Clercs et Emp. Notaires",["CRPCEN","1"]],
["Organisme 091007311",["MGEN","3"]],
["Organisme 091007971" ,[ "MGEN","3"]],
["Organisme 091007861" ,[ "MGEN","3"]],
["Organisme 91919000" ,[ "MGEN","3"]],
["Organisme 01908000",["CPRPF RG","1"]],
["CNMSS Affilies",["DDFIP DU VAR","1"]],
["Organisme CB1010000",["SWISSLIFE PREVOYANCE ET SANT","1"]],
["Organisme NR0010000",["MNT SANTE PRESTATION RC BRED", "1"]]
]);