// Définition de substitutions NOEMIE par défaut

const NoemieSubstitutionTableDefaut = JSON.stringify([
["Toulouse",[ "CPAM TOULOUSE","1"]],
["Bordeaux",[ "CPAM BORDEAUX","1"]],
["Albi",[ "CPAM ALBI","1"]],
["Mont de Marsan",["CPAM MONT DE MARSAN","1"]],
["CPAM de Rouen-Elbeuf-Dieppe-Seine-Maritime",["CPAM R.E.D.76","1"]],
["Pau",["CPAM PAU","1"]],
["Paris",["CPAM 75 PRESTATIONS","1"]],
["Agen",["CPAM AGEN","1"]],
["Nice",["CPAM 061 NICE","1"]],
["Bayonne",["CPAM DE BAYONNE","1"]],
["La Rochelle",["CPAM DE LA ROCHELLE","1"]],
["Rodez",["CPAM RODEZ","1"]],
["Perigueux",["CPAM PERIGUEUX","1"]],
["Carcassonne",["CPAM CARCASSONNE","1"]],
["Vannes",["CPAM DU MORBIHAN - COURANT","1"]],
["Tarbes",["CPAM TARBES","1"]],
["Versailles",["CPAM DES YVELINES","1"]],
["Organisme 901",["CAVIMAC","1"]],
["Melun Rubelles",["CPAM 77","1"]],
["Nanterre",["CPAM HAUTS DE SEINE SEPA","1"]],
["Mutuelle Interiale",["INTERIALE - GESTION RO","1"]],
["Caisse de Ret.et Prev. Clercs et Emp. Notaires",["CRPCEN","1"]],
["CNMSS Affilies",["DDFIP DU VAR","1"]],
["Organisme 091007311",["MGEN","3"]],
["Organisme 091007971" ,[ "MGEN","3"]],
["Organisme 091007861" ,[ "MGEN","3"]],
["Organisme 91919000" ,[ "MGEN","3"]],
["MGP Bourg en Bresse",["SECURITE SOCIALE MGP","1"]],
["Organisme 004110000",["CAISSE PREVOYANCE ET RETRAIT","1"]],
["Organisme SO0010000",["CETIP CETIP","0"]],
["Organisme SP0080000" ,[ "CETIP CETIP","0"]],
["Organisme AL0010000",[ "ALMERYS","1"]],
["Organisme VM0030000",["HARMONIE MUTUELLES","1"]],
["Organisme VM0010000",["VIAMEDIS","1"]],
["Organisme AC0010000",["ACTIL SAS","1"]],
["Organisme 01908000",["CPRPF RG","1"]],
["Organisme CB1010000",["SWISSLIFE PREVOYANCE ET SANT","1"]],
["Organisme NR0010000",["MNT SANTE PRESTATION RC BRED", "1"]]
]);