// Définition de substitutions NOEMIE par défaut
                        "TOULOUSE": "CPAM TOULOUSE",
                        "BORDEAUX": "CPAM BORDEAUX",
                        "ALBI": "CPAM ALBI",
                        "MONT DE MARSAN":"CPAM MONT DE MARSAN",
                        "CPAM de Rouen-Elbeuf-Dieppe-Seine-Maritime":"CPAM R.E.D.76",
                        "PAU":"CPAM PAU",
                        "PARIS":"CPAM 75 PRESTATIONS",
                        "AGEN":"CPAM AGEN",
                        "NICE":"CPAM 061 NICE",
                        "BAYONNE":"CPAM DE BAYONNE",
                        "LA ROCHELLE":"CPAM DE LA ROCHELLE",
                        "RODEZ":"CPAM RODEZ",
                        "PERIGUEUX":"CPAM PERIGUEUX",
                        "CARCASSONNE":"CPAM CARCASSONNE",
                        "VANNES":"CPAM DU MORBIHAN - COURANT",
                        "TARBES":"CPAM TARBES",
                        "VERSAILLES":"CPAM DES YVELINES",
                        "Organisme 901":"CAVIMAC",
                        "MELUN RUBELLES":"CPAM 77",
                        "Mutuelle INTERIALE":"INTERIALE - GESTION RO",
                        "NANTERRE":"CPAM HAUTS DE SEINE SEPA",
                        "Organisme 004110000":"CAISSE PREVOYANCE ET RETRAIT",
                        "MGP BOURG EN BRESSE":"SECURITE SOCIALE MGP",
                        "Organisme SO0010000":"CETIP CETIP",
                        "Organisme AL0010000": "ALMERYS",
                        "Organisme SP0080000" : "CETIP CETIP",
                        "Organisme VM0030000":"HARMONIE MUTUELLES",
                        "Organisme VM0010000":"VIAMEDIS",
                        "Organisme AC0010000":"ACTIL SAS",
                        "Caisse de Ret.et Prev. Clercs et Emp. Notaires":"CRPCEN",
                        "Organisme 091007311":"MGEN",
                        "Organisme 091007971" : "MGEN",
                        "Organisme 091007861" : "MGEN",
                        "Organisme 91919000" : "MGEN",
                        "Organisme 01908000":"CPRPF RG",
                        "CNMSS Affilies":"DDFIP DU VAR",
                        "Organisme CB1010000":"SWISSLIFE PREVOYANCE ET SANT",
                        "Organisme NR0010000":"MNT SANTE PRESTATION RC BRED"